#!/bin/bash
useradd -G $gid -o -u $uid $user
mkdir -p /home/$user/.vnc; printf "$pw" | vncpasswd -f > /home/$user/.vnc/passwd
chmod 600 /home/$user/.vnc/passwd
cp /data/.xinitrc /home/$user/
cp /data/.xinitrc /etc/X11/xinit/xinitrc
chown -R $user /home/$user
echo "$user ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
runuser -l $user -c "vncserver -fg -autokill"
